// This code was generated by JapaneseC Language Transpiler.
#include <locale.h>//JCLによって自動生成されました
//calculator.jc;
//簡単な計算機プログラム;
#include <stdio.h>

int main(){
    setlocale(LC_ALL, "ja_JP.UTF-8");//JCLによって自動生成されました
    int a, b, result;
    char operator;
    
    printf("=== 簡単な計算機 ===\n");
    fflush(stdout); //JCLによって自動生成されました
    printf("最初の数字を入力してください: ");
    fflush(stdout); //JCLによって自動生成されました
    scanf("%d", &a);
    
    // バッファクリア用のgetchar()を追加;
    getchar(); // 改行文字を消費;
    
    printf("演算子を入力してください (+, -, *, /): ");
    fflush(stdout); //JCLによって自動生成されました
    scanf(" %c", &operator);
    
    printf("次の数字を入力してください: ");
    fflush(stdout); //JCLによって自動生成されました
    scanf("%d", &b);
    
    if(operator == '+'){
        result = a + b;
        printf("%d + %d = %d\n", a, b, result);
        fflush(stdout); //JCLによって自動生成されました
    }else if(operator == '-'){
        result = a - b;
        printf("%d - %d = %d\n", a, b, result);
        fflush(stdout); //JCLによって自動生成されました
    }else if(operator == '*'){
        result = a * b;
        printf("%d * %d = %d\n", a, b, result);
        fflush(stdout); //JCLによって自動生成されました
    }else if(operator == '/'){
        if(b != 0){
            result = a / b;
            printf("%d / %d = %d\n", a, b, result);
            fflush(stdout); //JCLによって自動生成されました
        }else{
            printf("エラー: ゼロで割ることはできません\n");
            fflush(stdout); //JCLによって自動生成されました
        }
    }else{
        printf("エラー: 無効な演算子です\n");
        fflush(stdout); //JCLによって自動生成されました
    }
    
    return 0;
}